# Generated by Django 3.1.1 on 2020-09-23 08:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrects', models.IntegerField(default=0)),
                ('wrongs', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('time_taken', models.TimeField(default=datetime.time(0, 0))),
                ('on_which_date', models.TimeField(default=datetime.date(2020, 9, 23))),
                ('label', models.CharField(blank=True, choices=[('Y', 'yesterday'), ('N', 'Not needed But usefull information'), ('T', 'todays')], max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
