# Generated by Django 3.1.1 on 2020-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'Not needed But usefull information'), ('T', 'todays'), ('Y', 'yesterday')], max_length=1, null=True),
        ),
    ]
