# Generated by Django 3.1.1 on 2020-09-25 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200923_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='label',
            field=models.CharField(blank=True, choices=[('Y', 'yesterday'), ('N', 'Not needed But usefull information'), ('T', 'todays')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='on_which_date',
            field=models.DateField(default=datetime.date(2020, 9, 25)),
        ),
    ]
