# Generated by Django 3.1.1 on 2020-09-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200925_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'Not needed But usefull information'), ('Y', 'yesterday'), ('T', 'todays')], max_length=1, null=True),
        ),
    ]
