# Generated by Django 3.1.1 on 2020-09-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200925_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='label',
        ),
    ]
