# Generated by Django 3.1.1 on 2020-09-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_score_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='on_which_date',
        ),
        migrations.RemoveField(
            model_name='score',
            name='time_taken',
        ),
    ]
