# Generated by Django 3.1.1 on 2020-09-26 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200925_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_taken',
            field=models.TimeField(default=datetime.time, null=True),
        ),
    ]
