# Generated by Django 3.1.1 on 2020-09-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200926_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='corrects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='wrongs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
