# Generated by Django 3.1.1 on 2020-09-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200926_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='label',
            field=models.CharField(blank=True, choices=[('Y', 'yesterday'), ('T', 'todays'), ('N', 'Not needed But usefull information')], default='T', max_length=1, null=True),
        ),
    ]
