# Generated by Django 3.1.1 on 2020-09-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_score_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='label',
            field=models.CharField(blank=True, choices=[('T', 'todays'), ('Y', 'yesterday'), ('N', 'Not needed But usefull information')], default='T', max_length=1, null=True),
        ),
    ]
